#INCLUDE 'RWMake.ch'
#INCLUDE 'Totvs.ch'
#INCLUDE 'ParmType.ch'
#INCLUDE 'FwBrowse.ch'

Static _cVersao		:= '1.21'						AS Character
Static _cDtVersao	:= '03/03/2026'					AS Character

//-------------------------------------------------------------------------------------------------
/*/{Protheus.doc} CXUpdBatch
@description	Gera o lote para aplicação de atualizações usando o UpdBatch, a partir diretamente
				dos arquivos zip da Totvs
@autor			Cirilo Rocha
@since			31/07/2025
/*/
//-------------------------------------------------------------------------------------------------
//O SOFTWARE É FORNECIDO "TAL COMO ESTÁ", SEM GARANTIA DE QUALQUER TIPO, EXPRESSA OU IMPLÍCITA,
//INCLUINDO MAS NÃO SE LIMITANDO A GARANTIAS DE COMERCIALIZAÇÃO, ADEQUAÇÃO A UMA FINALIDADE
//ESPECÍFICA E NÃO INFRACÇÃO. EM NENHUM CASO OS AUTORES OU TITULARES DE DIREITOS AUTORAIS
//SERÃO RESPONSÁVEIS POR QUALQUER REIVINDICAÇÃO, DANOS OU OUTRA RESPONSABILIDADE, SEJA 
//EM AÇÃO DE CONTRATO OU QUALQUER OUTRA FORMA, PROVENIENTE, FORA OU RELACIONADO AO SOFTWARE. 
//
//                    *** USE A VONTADE, POR SUA CONTA E RISCO ***
//-------------------------------------------------------------------------------------------------
// TODO - MELHORIA FUTURA : CRIAR PROCESSO PARA TAMBÉM APLICAR OS PACOTES PTM
#DEFINE _LINHA_			StrZero(ProcLine(),5)
#DEFINE _NomeProg_		RetFileName(ProcSource())
#DEFINE _MsgLinha_		_NomeProg_+'('+_LINHA_+')'
#Define _LINOK_			'S'+_LINHA_
#Define _LINERRO_		'E'+_LINHA_
#Define _LINALERT_		'A'+_LINHA_
//-------------------------------------------------------------------------------------------------
User Function CXUpdBatch()

	//-- Declaração de Variáveis ----------------------------------------------
	Local lOK										AS Logical

	If Select('SX2') == 0	//-- Ambiente não aberto, faz a carga
		sfAbreAmbiente({|| lOK	:= sfUpdBatchMain(), oMainWnd:End()	})
	Else
		lOK	:= sfUpdBatchMain()
	EndIf

	//-- Se gerou os pacotes chama o UpdBatch!
	If lOK
		UpdBatch()
	EndIf

Return
//-------------------------------------------------------------------------------------------------
Static Function sfUpdBatchMain()					AS Logical

	//-- Declaração de Variáveis ----------------------------------------------
	Local aSM0			:= FWLoadSM0()				AS Array
	Local cArquivos									AS Character
	Local lOK										AS Logical
	Local nX										AS Numeric

	Private aEmpresas	:= {}						AS Array
	Private aArquivos	:= {}						AS Array
	Private aPacotes	:= {}						AS Array
	Private cDescPct								AS Character
	Private cPathTmp								AS Character
	Private cPathUpd								AS Character

	//-- Preciso ter alguma tela de interface para que o sistema abra depois a tela de seleção de arquivos
	FwAlertInfo('<h3>'+'Esta rotina tem objetivo de criar um lote de atualizações a serem aplicadas'+;
				' com o UpdBatch.'+CRLF+CRLF+;
				'Permite selecionar os pacotes de atualização diretamente dos arquivos zip da Totvs.'+CRLF+CRLF+;
				'By Cirilo Rocha'+;
				'</h3>',_MsgLinha_+' - v'+_cVersao+' - '+_cDtVersao)

	//-------------------------------------------------------------------------
	cDescPct	:= '### CXUpdBatch - '+Transform(DtoS(Date()),"@R 9999/99/99")+'-'+Time()+' ###'
	cPathTmp	:= '\temp\'+GetNextAlias()+'\'
	cPathUpd	:= GetSystemLoadDir()+'updbatch\'

	If .Not. FWMakeDir(cPathTmp,.T.)	;	Return .F.		;	EndIf	//-- Cria diretório / pasta (cria toda a estrutura)
	If .Not. sfUpdPend()				;	Return .F.		;	EndIf	//-- Tem update pedente?

	For nX := 1 to Len(aSM0)
		If aScan(aEmpresas,{|x| x['code'] == aSM0[nX][SM0_GRPEMP] }) == 0
			aAdd(aEmpresas,	{									;
								'mark':	.T.						;
							,	'code':	aSM0[nX][SM0_GRPEMP]	;
							,	'name':	aSM0[nX][SM0_NOMECOM]	;
							})
		EndIf
	Next nX

	//-- Seleciona os pacotes de atualização
	cArquivos	:= sfGetUpdates()
	If Empty(cArquivos)
		FwAlertError('Nenhum arquivo selecionado.',_MsgLinha_)
		Return .F.
	EndIf
	aArquivos	:= sfSeparaArq(cArquivos)

	//-- Extrair arquivos para a pasta temporária
	Processa( {|| sfExtraiPct(aArquivos) },_MsgLinha_+' - Extraindo pacotes', 'Aguarde...',.F. )
	
	cDescPct	:= FWInputBox('Digite uma descrição para o conjunto de atualizações',cDescPct)
	If Empty(cDescPct)
		lOk	:= .F.
	Else
		If 	sfSelectPcts(aPacotes) .And. ;
			sfSelectEmp()

			lOK	:= 	sfGravaUpd(aPacotes)
		EndIf
	EndIf

	FWMsgRun(,{|| FWDirRemove(cPathTmp,.F.,.T.) },_MsgLinha_+' - Apagando arquivos temporários','Aguarde...')	//-- Apaga o diretório temporário

Return lOK

//-------------------------------------------------------------------------------------------------
/*/{Protheus.doc} sfGetUpdates
@description	Função para selecionar os arquivos de update
@autor			Cirilo Rocha
@since			27/07/2025
/*/
//-------------------------------------------------------------------------------------------------
Static Function sfGetUpdates()						AS Character

	//-- Declaração de Variáveis ----------------------------------------------
	Local aRet										AS Array
	Local cRet										AS Character
	Local cDirInicial:= 'C:\Protheus\'				AS Character
	Local cProfSecao:= RetFileName(ProcSource())	AS Character
	Local cProfChave:= ProcName()					AS Character
	Local cMascara	:= '*.zip'						AS Character	//-- Mascara e Salvar não devem ser informados com diretórios e tFileDialog
	Local lSalvar	:= .F.							AS Logical
	Local nOpcoes	:= nOr(GETF_LOCALHARD,GETF_NETWORKDRIVE,GETF_MULTISELECT)	AS Numeric

	Local cDrive,cDir,cFile,cExten					AS Character

	//-------------------------------------------------------------------------
	cDir	:= fwGetProfString(cProfSecao,cProfChave,cDirInicial,.T.)	//-- Carrega último caminho utilizado

	cRet    := tFileDialog(	cMascara											,;	//01 cMascara
							_MsgLinha_+' Os pacotes para atualização: '			,;	//02 cTitulo
							1													,;	//03 nDef
							IIf(ExistDir(cDir),cDir,cDirInicial)				,;	//04 cDirInicial
							lSalvar												,;	//05 lSalvar
							nOpcoes	    										)	//06 nOpcoes
	
	//-- Tratamento de erros para WebApp (pode não ser necessário no futuro)
	aRet	:= sfSeparaArq(cRet)
	SplitPath( aRet[1] , @cDrive, @cDir, @cFile, @cExten )
	If BitAnd(nOpcoes,GETF_RETDIRECTORY)		//-- Diretórios
		If .Not. ExistDir(cRet)
			FwAlertError('Diretório informado '+cRet+' NÃO existe.',_MsgLinha_)
			cRet	:= ''
		EndIf		
	ElseIf .Not. Empty(cRet)					//-- Arquivos
		If Empty(cFile)
			FwAlertError('Nenhum nome de arquivo informado.',_MsgLinha_)
			cRet	:= ''
		ElseIf 	.Not. lSalvar .And. ;
				.Not. File(aRet[1])				//-- Valida se arquivo existe
			FwAlertError('Arquivo informado '+cRet+' NÃO existe.',_MsgLinha_)
			cRet	:= ''
		EndIf
	EndIf
	
	//-- Remove os caracteres especiais se houver
	If lSalvar
		cFile	:= FwNoAccent(cFile)
		cRet	:= cDrive+cDir+cFile+cExten
	EndIf

	//-- Salva o diretório atual que o usuário utilizou -----------------------
	If .Not. Empty(cRet)
		fwWriteProfString(cProfSecao,cProfChave,cDrive+cDir,.T.) //-- Guarda o diretório atual
	EndIf

Return cRet

//-------------------------------------------------------------------------------------------------
/*/{Protheus.doc} sfExtraiPct
@description	Extrai o pacote para o diretório temporário e lê os metadados
@autor			Cirilo Rocha
@since			27/07/2025
/*/
//-------------------------------------------------------------------------------------------------
Static Function sfExtraiPct(aArquivos	AS Array)	AS Logical

	//-- Declaração de Variáveis ----------------------------------------------
	Local aArqZip	:= {}							AS Array
	Local cArqSDF	:= ''							AS Character
	Local cTemp										AS Character
	Local nX,nP										AS Numeric
	Local nRet										AS Numeric

	//-- Parâmetros da Rotina -------------------------------------------------
	ParamType 0		VAR aArquivos		AS Array

	//-------------------------------------------------------------------------
	ProcRegua(Len(aArquivos))
	For nX := 1 to Len(aArquivos)
		
		IncProc('Extraindo pacote '+StrZero(nX,2)+' de '+StrZero(Len(aArquivos),2),_MsgLinha_)
		ProcessMessages()

		aAdd(aPacotes,	{											;
							'mark': 	.F.							;
						,	'data': 	'ERRO'						;
						,	'release': 	'ERRO'						;
						,	'nome': 	RetFileName(aArquivos[nX])	;
						,	'arquivo':	RTrim(aArquivos[nX])		;
						,	'path':		cPathTmp+StrZero(nX,2)+'\'	;
						,	'erro':		.F.							;
						,	'msg' :		''							;
						,	'json_pkg':	JsonObject():New()			;
						})

		//-- Se os arquivos estiverem local, faço uma verificação prévia antes de enviar para o servidor,
		// se já estiverem lá por conta do WebApp não preciso fazer essa verificação
		If .Not. ( Upper(GetTempPath(.T.,.T.)) $ Upper(aArquivos[nX]) )	//-- Se NÃO está no diretório do WebApp, ou seja, diretório local
			aArqZip	:= FListZip( aArquivos[nX],@nRet)
			If nRet < 0
				aPacotes[nX]['msg']  := _LINERRO_+' - Erro ao compactar arquivo: '+aArquivos[nX]
				aPacotes[nX]['erro'] := .T.
				Loop
			EndIf

			If aScan(aArqZip,{|x| x[1] == 'sdf/bra/'}) <= 0
				aPacotes[nX]['msg']  := _LINERRO_+' - Pacote NÃO possui o diretório \sdf\bra\'
				aPacotes[nX]['erro'] := .T.
				Loop
			EndIf

			If aScan(aArqZip,{|x| x[1] == 'sdf/bra/sdfbra.txt'}) <= 0
				aPacotes[nX]['msg']  := _LINERRO_+' - Pacote NÃO possui o arquivo sdfbra.txt'
				aPacotes[nX]['erro'] := .T.
				Loop
			EndIf
		EndIf

		//-- Copia o arquivo para o diretório temporário
		//If .Not. CpyT2S(aArquivos[nX],cPathTmp,.F.,.F.,500000)	//-- Buffer de 500k melhora a performance
		If .Not. __CopyFile(aArquivos[nX],cPathTmp+RTrim(ExtractFile(aArquivos[nX])),,,,500000)		//-- Buffer de 500k melhora a performance
			//-- PRECISO USAR A FUNÇÃO __CopyFile, POIS A CpyT2S TEM PROBLEMA COM O PATH DO WEBAPP 10.1.3 E tFileDialog
			aPacotes[nX]['msg']  := _LINERRO_+' - Erro ao copiar arquivo para o servidor'
			aPacotes[nX]['erro'] := .T.
			Loop
		EndIf
		aPacotes[nX]['arquivo' ]	:= cPathTmp+RTrim(ExtractFile(aArquivos[nX]))

		If .Not. FWMakeDir(aPacotes[nX]['path'],.T.)
			aPacotes[nX]['msg']  := _LINERRO_+' - Não foi possível criar o diretório: '+aPacotes[nX]['path']
			aPacotes[nX]['erro'] := .T.
			Loop
		EndIf

		If FUnZip( aPacotes[nX]['arquivo'] , aPacotes[nX]['path'] ) <> 0
			aPacotes[nX]['msg']  := _LINERRO_+' - Erro ao extrair o pacote.'
			aPacotes[nX]['erro'] := .T.
			Loop
		EndIf

		aPacotes[nX]['path'] += 'sdf\bra\'
		If .Not. ExistDir(aPacotes[nX]['path'])
			aPacotes[nX]['msg']  := _LINERRO_+' - Pacote NÃO possui o diretório \sdf\bra\'
			aPacotes[nX]['erro'] := .T.
			Loop
		EndIf

		If .Not. File(aPacotes[nX]['path']+'sdfbra.txt')
			aPacotes[nX]['msg']  := _LINERRO_+' - Pacote NÃO possui o arquivo sdfbra.txt'
			aPacotes[nX]['erro'] := .T.
			Loop
		EndIf
		
		cArqSDF	:= sfReadFile(aPacotes[nX]['path']+'sdfbra.txt')
		If Empty(cArqSDF)
			aPacotes[nX]['msg']  := _LINERRO_+' - ERRO: Arquivo sdfbra.txt vazio.'
			aPacotes[nX]['erro'] := .T.
			Loop
		EndIf

		nP		:= At('EM_PRJDES ', cArqSDF)		//-- Posição do campo EM_PRJDES
		If nP <= 0
			nP		:= At('FL_DESCRI ', cArqSDF)	//-- Posição do campo FL_DESCRI
			If nP <= 0
				aPacotes[nX]['msg']  := _LINERRO_+' - Arquivo sdfbra.txt NÃO possui o campo FL_DESCRI'
				aPacotes[nX]['erro'] := .T.
				Loop
			Else
				cTemp	:= RTrim(SubStr(cArqSDF, nP+10,100))
				aPacotes[nX]['json_pkg']['fl_descri']	:= cTemp
			EndIf
		Else
			cTemp	:= RTrim(SubStr(cArqSDF, nP+10,100))
			aPacotes[nX]['json_pkg']['em_prjdes']	:= cTemp
		EndIf
		aPacotes[nX]['nome']	:= cTemp	//-- Extrai o campo EM_RELEASE ou FL_CPMARK

		nP		:= At('FL_DATE   ', cArqSDF)		//-- Posição do campo FL_DATE
		If nP <= 0
			aPacotes[nX]['msg']  := _LINERRO_+' - Arquivo sdfbra.txt NÃO possui o campo FL_DATE'
			aPacotes[nX]['erro'] := .T.
			Loop
		EndIf
		cTemp	:= RTrim(SubStr(cArqSDF, nP+10, 10))
		aPacotes[nX]['json_pkg']['fl_date']	:= cTemp
		aPacotes[nX]['data']	:= cTemp	//-- Extrai o campo FL_DATE

		nP		:= At('FL_TIME   ', cArqSDF)		//-- Posição do campo FL_TIME
		If nP > 0
			aPacotes[nX]['json_pkg']['fl_time']	:= RTrim(SubStr(cArqSDF, nP+10, 10))
		EndIf

		nP		:= At('FL_APMODE ', cArqSDF)		//-- Posição do campo FL_APMODE
		If nP > 0
			aPacotes[nX]['json_pkg']['fl_apmode']	:= RTrim(SubStr(cArqSDF, nP+10, 10))
		EndIf

		nP		:= At('PR_IDENT  ', cArqSDF)		//-- Posição do campo PR_IDENT
		If nP > 0
			aPacotes[nX]['json_pkg']['pr_ident']	:= RTrim(SubStr(cArqSDF, nP+10, 10))
		EndIf

		nP		:= At('PK_IDENT  ', cArqSDF)		//-- Posição do campo PK_IDENT
		If nP > 0
			aPacotes[nX]['json_pkg']['pk_ident']	:= RTrim(SubStr(cArqSDF, nP+10, 10))
		EndIf

		nP		:= At('EM_RELEASE', cArqSDF)		//-- Posição do campo EM_RELEASE
		If nP <= 0
			nP		:= At('FL_CPMARK ', cArqSDF)	//-- Posição do campo FL_CPMARK
			If nP <= 0
				aPacotes[nX]['msg']  := _LINERRO_+' - Arquivo sdfbra.txt NÃO possui o campo FL_CPMARK'
				aPacotes[nX]['erro'] := .T.
				Loop
			Else
				cTemp	:= RTrim(SubStr(cArqSDF, nP+10, 10))
				aPacotes[nX]['json_pkg']['fl_cpmark']	:= cTemp
			EndIf
		Else
			cTemp	:= RTrim(SubStr(cArqSDF, nP+10, 10))
			aPacotes[nX]['json_pkg']['em_release']	:= cTemp
		EndIf
		aPacotes[nX]['release']	:= cTemp	//-- Extrai o campo EM_RELEASE ou FL_CPMARK
		
		nP		:= At('FL_NOTICE ', cArqSDF)		//-- Posição do campo FL_NOTICE
		If nP > 0
			aPacotes[nX]['json_pkg']['fl_notice']	:= RTrim(SubStr(cArqSDF, nP+10, 100))
		EndIf

		nP		:= At('FL_ECPMARK', cArqSDF)		//-- Posição do campo FL_ECPMARK
		If nP > 0
			aPacotes[nX]['json_pkg']['fl_ecpmark']	:= RTrim(SubStr(cArqSDF, nP+10, 150))
		EndIf

		nP		:= At('EM_ENCREL', cArqSDF)		//-- Posição do campo EM_ENCREL
		If nP > 0
			aPacotes[nX]['json_pkg']['em_encrel']	:= RTrim(SubStr(cArqSDF, nP+10, 30))
		EndIf

		nP		:= At('EM_PRJCOD ', cArqSDF)		//-- Posição do campo EM_PRJCOD
		If nP > 0
			aPacotes[nX]['json_pkg']['em_prjcod']	:= RTrim(SubStr(cArqSDF, nP+10, 10))
		EndIf

		nP		:= At('EM_PRJVER ', cArqSDF)		//-- Posição do campo EM_PRJVER
		If nP > 0
			aPacotes[nX]['json_pkg']['em_prjver']	:= RTrim(SubStr(cArqSDF, nP+10, 10))
		EndIf	

		aPacotes[nX]['mark']	:= .T.
		aPacotes[nX]['erro']	:= .F.
	Next nX

Return .T.

//-------------------------------------------------------------------------------------------------
/*/{Protheus.doc} sfReadFile
@description	Leitura de um arquivo de texto, sem limitação de 64k do MemoRead
@autor			Cirilo Rocha
@since			27/07/2025
/*/
//-------------------------------------------------------------------------------------------------
Static Function sfReadFile(cFile	AS Character)	AS Character
	
	//-- Declaração de Variáveis ----------------------------------------------
	Local oFile										AS Object
	Local cRet	:= ''								AS Character
	
	//-- Parâmetros da Rotina -------------------------------------------------
	ParamType 0		VAR cFile		AS Character
	
	//-------------------------------------------------------------------------
	oFile := FWFileReader():New(cFile,/*xBreakLine*/)
	oFile:SetBufferSize(50000)	//-- Aumento o buffer vai agilizar bastante a leitura
	If (oFile:Open())
		cRet	:= oFile:FullRead()
		If Empty(cRet)
			FwAlertError('ERRO: Arquivo vazio.',_MsgLinha_)
		EndIf
	Else
		FwAlertError('ERRO: Na leitura do arquivo '+cFile+CRLF+;
					oFile:Error():Message)
	EndIf
	oFile:Close()		//-- Fecha arquivo
	FreeObj(oFile)

Return cRet

//-------------------------------------------------------------------------------------------------
/*/{Protheus.doc} sfSeparaArq
@description	Função para quebrar a lista de arquivos da função tFileDialog, quando multiseleção
				 para conseguir identificar arquivos que contenham ; no nome.                     
@autor			Cirilo Rocha
@since			28/07/2025
/*/
//-------------------------------------------------------------------------------------------------
Static Function sfSeparaArq(cArquivos	AS Character);	//01 cArquivos
													AS Array
	//-- Declaração de Variáveis ----------------------------------------------
	Local aArquivos	:= {}							AS Array
	Local nPAtu										AS Integer
	Local nPQueb									AS Integer
	Local nPFim										AS Integer

	//-- Parâmetros da Rotina -------------------------------------------------
	ParamType 0		VAR cArquivos		AS Character

	//---------------------------------------------------------------------------------------------
	////TESTE WINDOWS
	//cArquivos:=	"c:\temp\carlitolima13.jpg;"+;
	//			"c:\temp\erro.log;"+;
	//			"c:\temp\getfols-1200 - 2022-12-12-08;47;27.jpg;"+;
	//			"c:\temp\rgperc29 - 2022-12-08-17;18;29.sql"
	////TESTE LINUX
	//cArquivos:=	"/tmp/carlitolima13.jpg;"+;
	//			"/tmp/erro.log;"+;
	//			"/tmp/getfols-1200 - 2022-12-12-08;47;27.jpg;"+;
	//			"/tmp/rgperc29 - 2022-12-08-17;18;29.sql"

	//---------------------------------------------------------------------------------------------
	If At(' | ',cArquivos)	//cGetFile antiga
		aArquivos	:= StrTokArr2(cArquivos,' | ',.F.)
	Else
		nPAtu	:= 1
		nPQueb	:= At(':',cArquivos)
		If nPQueb > 0					//Windows!
			While .T.
				//Busca proxima quebra
				nPQueb	:= At(':',cArquivos,nPAtu+3)		//Pula o primeiro c:\
				nPFim	:= Rat(';',Left(cArquivos,nPQueb))	//+3 para pular o próprio c:\ do arquivo atual
				If nPFim == 0
					Exit
				Else
					aAdd(aArquivos,AllTrim(SubStr(cArquivos,nPAtu,nPFim-nPAtu)))
					nPAtu	:= nPFim+1
				EndIf
			EndDo
		ElseIf At(';/',cArquivos)		//Linux
			While .T.
				//Busca proxima quebra
				nPFim	:= At(';/',cArquivos,nPAtu)
				If nPFim == 0
					Exit
				Else
					aAdd(aArquivos,SubStr(cArquivos,nPAtu,nPFim-nPAtu))
					nPAtu	:= nPFim+1
				EndIf
			EndDo
		EndIf
		aAdd(aArquivos,AllTrim(SubStr(cArquivos,nPAtu)))	//Último arquivo ou 1 Arquivo
	EndIf

Return aArquivos

//-------------------------------------------------------------------------------------------------
/*/{Protheus.doc} sfSelectPcts
@description	Função para selecionar os pacotes de atualização e exibir os dados dos mesmos em um Browse.
@autor			Cirilo Rocha
@since			28/07/2025
/*/
//-------------------------------------------------------------------------------------------------
Static Function sfSelectPcts(aDados	AS Array)		AS Logical
	
	//-- Declaração de Variáveis ----------------------------------------------
	Local lOk		:= .F.							AS Logical
	Local lMarca	:= .F.							AS Logical	//-- Como o browse vem pré-marcado, o botão desmarca

	//-- Deixei privados caso alguma função chamada precise dos dados
	Private oDlgModal,oDlg,oLst,oPnl				AS Object
	
	//-- Parâmetros da Rotina -------------------------------------------------
	ParamType 0		VAR aDados		AS Array

	//-------------------------------------------------------------------------
    oDlgModal  := FWDialogModal():New()
		oDlgModal:SetEscClose(.T.)
		oDlgModal:setTitle(_MsgLinha_+' - Selecione os Pacotes de Atualização - v'+_cVersao+' | '+_cDtVersao)
		oDlgModal:setSize(300, 600)	//-- Altura em pixels / 1.5
		oDlgModal:createDialog()

		oDlg := oDlgModal:getPanelMain()

		oPnl := tPanel():New(005,005,,oDlg,,,,,,__DlgWidth(oDlg)-10,__DlgHeight(oDlg)-15) //-- Preciso do Painel só para limitar o tamanho do browse
		oLst := FWFormBrowse():New()
		oLst:oConfig:nRowHeight	:= 25	//-- Reduzo um pouco a altura das linhas
		oLst:oConfig:nFontHeader:= 09	//-- Reduzo o tamanho da fonte
		oLst:oConfig:nFontBody	:= 10	//-- Reduzo o tamanho da fonte

		oLst:setDataArray()
		oLst:setArray( aDados )	//-- Seta o vetor a ser utilizado
		//oLst:disableConfig()
		oLst:disableReport()
		oLst:SetLocate()		//-- Habilita a Localização de registros
		oLst:bDelOk	:= {|| .F.}	//-- Não permite deletar linhas

		// Evento de DuploClick (troca o valor do primeiro elemento do Vetor)
		oLst:bLDblClick := {|| sfMarcaReg() }
		
		oLst:AddButton('Inverte Seleção', {|| aEval(oLst:oData:aArray,{|x| IIF(x['erro'],,x['mark'] := .Not. x['mark'])}),oLst:Refresh() })

		oLst:AddMarkColumns({|| If(aDados[oLst:nAt]['mark'],'LBTIK','LBNO') })	//-- Coluna Marca
		aTail(oLst:aColumns):bHeaderClick	:= {|| aEval(oLst:oData:aArray,{|x| IIf(x['erro'],, x['mark']:= lMarca ) }) , lMarca:=.Not.lMarca , oLst:Refresh() }	//-- Marca/Desmarca Todos

		// Monta a linha a ser exibina no Browse
		//               Descrição       bDados                        Tipo   Picture     Alinhamento        Tam Dec Edita
		oLst:addColumn({'Data'			,{|| aDados[oLst:nAt]['data'	]},'C',/*cPicture*/ , COLUMN_ALIGN_LEFT	, 08,00,.F.})
		oLst:addColumn({'Release'		,{|| aDados[oLst:nAt]['release'	]},'C',/*cPicture*/ , COLUMN_ALIGN_LEFT	, 10,00,.F.})
		oLst:addColumn({'Nome'			,{|| aDados[oLst:nAt]['nome'	]},'C',/*cPicture*/ , COLUMN_ALIGN_LEFT	, 50,00,.F.})
		oLst:addColumn({'Mensagem Erro'	,{|| aDados[oLst:nAt]['msg'		]},'C',/*cPicture*/ , COLUMN_ALIGN_LEFT	, 50,00,.F.})
		oLst:addColumn({'Arquivo'		,{|| aDados[oLst:nAt]['arquivo' ]},'C',/*cPicture*/ , COLUMN_ALIGN_LEFT	, 50,00,.F.})

		oLst:Activate(oPnl)

		//-----------------------------------------------------------------------------------------
		oDlgModal:addCloseButton({|| lOk := .F. , oDlgModal:DeActivate() }, 'Cancelar')
		oDlgModal:addOkButton({|| IIf((lOk := sfVldOK(oLst)),oDlgModal:DeActivate(),) }, 'OK')

	oDlgModal:Activate()

Return lOk

//-------------------------------------------------------------------------------------------------
/*/{Protheus.doc} sfMarcaReg
@description	Função para marcar/desmarcar o registro atual do Browse
@autor			Cirilo Rocha
@since			28/07/2025
/*/
//-------------------------------------------------------------------------------------------------
Static Function sfMarcaReg(	lMsg	AS Logical	)	//01 lMsg
	
	//-- Declaração de Variáveis ----------------------------------------------
	Local nAt	:= oLst:nAt							AS Numeric

	//-- Parâmetros da Rotina -------------------------------------------------
	Default lMsg	:= .T.

	//-- Marca/Desmarca o registro atual
	If oLst:oData:aArray[nAt]['erro']
		If lMsg
			FwAlertError('Não é possível marcar o registro com erro.',_MsgLinha_)
		EndIf
		Return
	Else
		oLst:oData:aArray[nAt]['mark'] := !oLst:oData:aArray[nAt]['mark']
	EndIf
	
Return

//-------------------------------------------------------------------------------------------------
/*/{Protheus.doc} sfAbreAmbiente
@description	Faz a abertura do ambiente Protheus
@autor			Cirilo Rocha
@since			28/07/2025
/*/
//-------------------------------------------------------------------------------------------------
Static Function sfAbreAmbiente(bFuncao	AS CodeBlock)		AS Logical
	
	//-- Declaração de Variáveis ----------------------------------------------
	Local aSM0										AS Array
	Local lRet	:= .F.								AS Logical
	Local nP										AS Numeric

	//-- Parâmetros da Rotina -------------------------------------------------
	ParamType 0		VAR bFuncao		AS Block

	//-------------------------------------------------------------------------
	OpenSm0()
	aSM0	:= FWLoadSM0()
	nP		:= aScan(aSM0,{|x| x[1] == '99' })
	If nP <= 0		; 	nP	:= 1		; 	EndIf

	RpcSetType(3)
	FWMsgRun(,;
			{||lRet := RPCSetEnv(	aSM0[nP][1]		;	//01 Empresa
								,	aSM0[nP][2]		;	//02 Filial
								,	/*cEnvUser*/	;	//03 Usuario
								,	/*cEnvPass*/	;	//04 Senha de Usuario
								,	/* cMod */		;	//05 Modulo (3ch)
								,	_NomeProg_		;	//06 Nome da Funcao
								,	/*aTables*/		;	//07 Tabelas para abrir
								,	/*lShowFinal*/	;	//08 Alimenta a variavel lMsFinalAuto
								,	.F.				;	//09 Gera mensagem de erro ao ocorrer erro ao checar a licenca
								,	.T.				;	//10 Pega a primeira filial do arquivo SM0 quando não passar a filial e realiza a abertura dos SXs
								,	.F.				;	//11 Faz a abertura da conexao com servidor do banco
								);
						},;
			_MsgLinha_+" - Montando Ambiente",;
			"Aguarde...")

	If .Not. lRet
		FwAlertWarning(	'Não foi possível montar o ambiente.',_MsgLinha_)
		Return .F.
	EndIf

	//PRECISO ABRIR OS SX'S AQUI PARA FUNCIONAR CORRETAMENTE
	OpenSm0()	//Abre o sigamat

//	__cUserID	:= '000000'
//	cUserName	:= 'Administrador'
	__cInternet	:= NIL			//-- Preciso colocar aqui para mostrar mensagens
	lMsHelpAuto	:= .F.			//-- Preciso colocar aqui para mostrar mensagens

	//-- Cria uma janela principal para trabalho
	Public oMainWnd					AS Object
	
	oMainWnd := TWindow():New( 000, 000, 600, 800, _MsgLinha_+'-oMainWnd-v'+_cVersao+' | '+_cDtVersao,,,,,,,,,,,,.T.,.T.,.T.,.T.,.T.)

	oMainWnd:Activate( 'MAXIMIZED', oMainWnd:bLClicked, oMainWnd:bRClicked, oMainWnd:bMoved,;
						oMainWnd:bResized, oMainWnd:bPainted, oMainWnd:bKeyDown, bFuncao ,;
						,,,,,,,,,, oMainWnd:bLButtonUp )

	RpcClearEnv()

Return lRet

//-------------------------------------------------------------------------------------------------
/*/{Protheus.doc} sfUpdPend
@description	Verifica se existe um update pendente
@autor			Cirilo Rocha
@since			31/07/2025
/*/
//-------------------------------------------------------------------------------------------------
Static Function sfUpdPend()							AS Logical

	//-- Declaração de Variáveis ----------------------------------------------
	Local cQuery	:= ''							AS Character
	Local cUpdate	:= ''							AS Character
	Local oQry										AS Object
	Local oStmUpd									AS Object
	Local ucQry										AS Variant

	Local lOK		:= .T.							AS Logical

	//-------------------------------------------------------------------------
	BeginContent Var cQuery AS SQL

	SELECT PARAM_VALUE,BA_DESCRI
	FROM TOP_PARAM
	FULL OUTER JOIN SYS_BATCH_UPDATE SU
		ON SU.D_E_L_E_T_<>'*'
		AND BA_BATCHID = PARAM_VALUE
	WHERE PARAM_NAME = 'PROTHEUS_BATCH_UPD'

	EndContent

	oQry	:= FwExecStatement():New(cQuery)
	oQry:openAlias(@ucQry)	//oQry:getFixQuery() retorna query processada
	If (ucQry)->(!EoF())
		If FwAlertNoYes('<H3>Existe um update pedente.'+CRLF+;
						'ID: '+(ucQry)->PARAM_VALUE+CRLF+;
						'Descrição: '+(ucQry)->BA_DESCRI+CRLF+;
						'DESEJA EXCLUIR E CRIAR UM NOVO ?</H3>',_MsgLinha_)

			BeginContent Var cUpdate AS SQL

			DELETE TOP_PARAM
			WHERE PARAM_VALUE = ? 

			EndContent

			oStmUpd := FWPreparedStatement():New(cUpdate)
			oStmUpd:SetString(1,(ucQry)->PARAM_VALUE)

			If TCSqlExec(oStmUpd:getFixQuery()) < 0	//Executa update no SQL
				FwAlertError(	'Erro na execução do update.'+CRLF+;
								TCSqlError(),_MsgLinha_)
			Else
				FWDirRemove(cPathUpd+AllTrim((ucQry)->PARAM_VALUE),,.T.)
				lOK	:= .T.
			EndIf
			oStmUpd:Destroy()		//-- Chama o destrutor
			FreeObj(oStmUpd)		//-- Destroi objeto
		Else
			lOK	:= .F.
		EndIf
	EndIf
	(ucQry)->(dbCloseArea()) //Fecha a query
	oQry:destroy()
	FreeObj(oQry)

Return lOK

//-------------------------------------------------------------------------------------------------
/*/{Protheus.doc} sfSelectPcts
@description	Função para selecionar os pacotes de atualização e exibir os dados dos mesmos em um Browse.
@autor			Cirilo Rocha
@since			28/07/2025
/*/
//-------------------------------------------------------------------------------------------------
Static Function sfSelectEmp()						AS Logical
	
	//-- Declaração de Variáveis ----------------------------------------------
	Local lOk		:= .F.							AS Logical
	Local lMarca	:= .F.							AS Logical	//-- Como o browse vem pré-marcado, o botão desmarca

	//-------------------------------------------------------------------------
	//-- Deixei privados caso alguma função chamada precise dos dados
	Private oDlgModal,oDlg,oLst,oPnl				AS Object
	
	//-------------------------------------------------------------------------
    oDlgModal  := FWDialogModal():New()
		oDlgModal:SetEscClose(.T.)
		oDlgModal:setTitle(_MsgLinha_+' - Selecione as Empresas para Aplicar')
		oDlgModal:setSize(280,280)	//-- Altura em pixels / 1.5
		oDlgModal:createDialog()

		oDlg := oDlgModal:getPanelMain()

		oPnl := tPanel():New(005,005,,oDlg,,,,,,__DlgWidth(oDlg)-10,__DlgHeight(oDlg)-15) //Preciso do Painel só para limitar o tamanho do browse
		oLst := FWFormBrowse():New()
		oLst:oConfig:nRowHeight	:= 25	//-- Reduzo um pouco a altura das linhas
		oLst:oConfig:nFontHeader:= 09	//-- Reduzo o tamanho da fonte
		oLst:oConfig:nFontBody	:= 10	//-- Reduzo o tamanho da fonte

		oLst:setDataArray()
		oLst:setArray( aEmpresas )	//-- Seta o vetor a ser utilizado
		//oLst:disableConfig()
		oLst:disableReport()
		oLst:SetLocate()			//-- Habilita a Localização de registros
		oLst:bDelOk	:= {|| .F. }	//-- Não permite deletar linhas

		// Evento de DuploClick (troca o valor do primeiro elemento do Vetor)
		oLst:bLDblClick := {|| aEmpresas[oLst:nAt]['mark'] := !aEmpresas[oLst:nAt]['mark'] }
		
		oLst:AddButton('Inverte Seleção', {|| aEval(oLst:oData:aArray,{|x| x['mark'] := .Not. x['mark']}) , oLst:Refresh() })

		oLst:AddMarkColumns({|| If(aEmpresas[oLst:nAt]['mark'],'LBTIK','LBNO') })	//-- Coluna Marca
		aTail(oLst:aColumns):bHeaderClick	:= {|| aEval(oLst:oData:aArray,{|x| x['mark']:= lMarca }) , lMarca:=.Not.lMarca , oLst:Refresh() }	//-- Marca/Desmarca Todos

		// Monta a linha a ser exibina no Browse
		//               Descrição       bDados                        Tipo   Picture     Alinhamento        Tam Dec Edita
		oLst:addColumn({'Empresa'		,{|| aEmpresas[oLst:nAt]['code']+'-'+aEmpresas[oLst:nAt]['name']},'C',/*cPicture*/ , COLUMN_ALIGN_LEFT	, 40,00,.F.})

		oLst:Activate(oPnl)

		//-----------------------------------------------------------------------------------------
		oDlgModal:addCloseButton({|| lOk := .F. , oDlgModal:DeActivate() }, 'Cancelar')
		oDlgModal:addOkButton({|| IIf((lOk := sfVldOK(oLst)),oDlgModal:DeActivate(),) }, 'OK')

	oDlgModal:Activate()

Return lOk

//-------------------------------------------------------------------------------------------------
/*/{Protheus.doc} sfVldOK
@description	Valida a seleção dos títulos, precisa ser selecionado pelo menos 1
@autor			Cirilo Rocha
@since			31/07/2025
/*/
//-------------------------------------------------------------------------------------------------
Static Function sfVldOK(oLst	AS Object)			AS Logical

	//-- Declaração de Variáveis ----------------------------------------------
	Local lRet		:= .F.							AS Logical
	Local nQtdReg	:= 0							AS Numeric
	
	//-- Parâmetros da Rotina -------------------------------------------------
	ParamType 0		VAR oLst		AS Object
	
	//-------------------------------------------------------------------------
	aEval(oLst:oData:aArray,{|x| IIf(x['mark'],nQtdReg++,) })
	
	If ( nQtdReg > 0 )
		lRet	:= .T.
	Else
		FwAlertError('Nenhum registro foi marcado. Selecione pelo menos 1 registro para prosseguir.',_MsgLinha_)
	EndIf

Return lRet

//-------------------------------------------------------------------------------------------------
/*/{Protheus.doc} sfGravaUpd
@description	Grava os dados para aplicação do update
@autor			Cirilo Rocha
@since			01/08/2025
/*/
//-------------------------------------------------------------------------------------------------
Static Function sfGravaUpd(aPacotes	AS Array)		AS Logical

	//-- Declaração de Variáveis ----------------------------------------------
	Local aEmpSel	:= {}							AS Array	//-- Array com as empresas selecionadas
	Local cUUID		:= Lower(FWUUIDv4())			AS Character
	Local jConfig									AS Json
	Local lErro		:= .F.							AS Logical
	Local nX										AS Numeric
	Local nSeq		:= 1							AS Numeric

	Local oStmUpd									AS Object
	Local cUpdate									AS Character

	//-- Parâmetros da Rotina -------------------------------------------------
	ParamType 0		VAR aPacotes		AS Array
	
	//-------------------------------------------------------------------------
	aEval(aEmpresas,{|x| If(x['mark'],aAdd(aEmpSel,x['code']),) })	//-- Cria um array com as empresas selecionadas

	//-- Monta o JSON de configuração
	jConfig	:= 	{								;
					'logprocess': 		.F.		;
				,	'logatualizacao':	.T.		;
				,	'logwarning': 		.F.		;
				,	'loginclusao': 		.F.		;
				,	'logcritical': 		.T.		;
				,	'oktoall': 			.T.		;
				,	'deletebkp': 		.T.		;
				,	'keeplog': 			.T.		;
				,	'empresas': 		aEmpSel	;
				,	'localizacao': 		'BRA'	;
				}

	Begin Transaction
		If oStmUpd == NIL
			BeginContent Var cUpdate

			INSERT INTO TOP_PARAM
			(PARAM_NAME,PARAM_SESSION,PARAM_VALUE)
			VALUES ( 'PROTHEUS_BATCH_UPD' , 0 , ? )

			EndContent
			oStmUpd := FWPreparedStatement():New(cUpdate)
		EndIf
		oStmUpd:SetString(1,cUUID)	//-- Seta o UUID gerado
		//oStmUpd:getFixQuery() retorna query processada
		If TCSqlExec(oStmUpd:getFixQuery()) < 0	//Executa update no SQL
			FwAlertError(	'Erro na execução do update.'+CRLF+;
							TCSqlError(),_MsgLinha_)
			DisarmTransaction()
			lErro	:= .T.
		EndIf
		oStmUpd:Destroy()		//-- Chama o destrutor
		FreeObj(oStmUpd)		//-- Destroi objeto

		dbUseArea(.T.,'TOPCONN', 'SYS_BATCH_UPDATE'		,'UPDCAB', .T., .F.)	//-- Abre tabelas para preencher
		dbUseArea(.T.,'TOPCONN', 'SYS_BATCH_UPDATE_SET'	,'UPDDET', .T., .F.)	//-- Abre tabelas para preencher

		RecLock('UPDCAB',.T.)		//-- Bloqueia o registro para edição
			UPDCAB->BA_BATCHID	:= cUUID
			UPDCAB->BA_DESCRI	:= cDescPct
			UPDCAB->BA_DATE		:= Date()
			UPDCAB->BA_TIME		:= Time()+'.000'
			UPDCAB->BA_LOCALIZ	:= "BRA"
			UPDCAB->BA_PARAM	:= jConfig:toJson()	//-- Seta o JSON de configuração
		UPDCAB->(MsUnLock())		//-- Desbloqueia o registro para edição
		
		For nX := 1 to Len(aPacotes)		//-- Percorre os pacotes selecionados
			If aPacotes[nX]['mark']
				RecLock('UPDDET',.T.)
					UPDDET->ST_BATCHID	:= cUUID							//-- Seta o UUID gerado
					UPDDET->ST_SEQ		:= StrZero(nSeq++,4)				//-- Sequência
					UPDDET->ST_SETID	:= 'set'+UPDDET->ST_SEQ				//-- Seta o ID
					UPDDET->ST_DESCRI	:= aPacotes[nX]['nome']				//-- Descrição
					UPDDET->ST_METADAT	:= aPacotes[nX]['json_pkg']:toJson()//-- Tipo de Metadado
					UPDDET->ST_STATUS	:= '1'								//-- Status pendente
				UPDDET->(MsUnLock())

				If .Not. sfMovArq(	aPacotes[nX]['path'],;
									cPathUpd+cUUID+'\'+UPDDET->ST_SETID+'\')	//-- Move a pasta para o diretório de atualização
					DisarmTransaction()
					lErro	:= .T.
					Exit
				EndIf
			EndIf
		Next nX

	End Transaction

	If lErro
		FWMsgRun(,{|| FWDirRemove(cPathUpd+cUUID,,.T.) },_MsgLinha_+' - Apagando temporários','Aguarde...')
	EndIf

Return .Not. lErro

//-------------------------------------------------------------------------------------------------
/*/{Protheus.doc} sfMovArq
@description	Move todos os arquivos de um diretório para outro
@autor			Cirilo Rocha
@since			01/08/2025
/*/
//-------------------------------------------------------------------------------------------------
Static Function sfMovArq(cDirOri	AS Character;
						,cDirDest	AS Character;
						)							AS Logical

	//-- Declaração de Variáveis ----------------------------------------------
	Local aArquivos	:= {}							AS Array
	Local lRet		:= .T.							AS Logical
	Local nX										AS Numeric

	//-- Parâmetros da Rotina -------------------------------------------------
	ParamType 0		VAR cDirOri		AS Character
	ParamType 1		VAR cDirDest	AS Character

	//-------------------------------------------------------------------------
	If .Not. FWMakeDir(cDirDest,.T.)
		Return .F.
	EndIf

	aArquivos := Directory(cDirOri + "\*.*")
	For nX := 1 to Len(aArquivos)
		If fRename(cDirOri+aArquivos[nX][1],cDirDest+ExtractFile(aArquivos[nX][1])) < 0
			FwAlertError(	'Erro ao mover o arquivo: '+aArquivos[nX][1]+CRLF+;
							cValToChar(fError()),_MsgLinha_)
			lRet	:= .F.
			Exit
		EndIf
	Next nX

Return lRet
